missing fields for Texture3DBase
Dav1dde/glamour pull request #25
Opened 2016-09-21 14:20 UTC by John-Colvin

2016-09-21 17:24 UTC, Dav1dde commented on glamour/texture.d
> +                        glTexImage1D, glTexImage2D, glTexImage3D glTexParameteri, glTexParameterf,
Missing comma, right?

2016-09-21 17:26 UTC, Dav1dde requested changes

2016-09-30 10:16 UTC, John-Colvin commented
fixed

2016-10-05 19:20 UTC, merged

2016-10-05 19:20 UTC, Dav1dde commented
Thanks!